name: Deploy to GitHub Pages
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy
      uses: peaceiris/actions-workflow@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: .
